version: 2.0

jobs:
    build:
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/matbilodeau.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "4e:ae:c5:01:39:ca:92:35:73:6d:8d:9a:8e:18:e3:db"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: git clone -b source git@github.com:matbilodeau.github.io.git public
            - run:
                name: Generate site
                working_directory: ~/matbilodeau.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - deploy:
                name: Deploy to Github Pages
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "mathieubilodeau000@gmail.com
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "Trigger deployment"
                    git push -q git@github.com:matbilodeau.github.io.git master

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: source
