#version: 2.0
#
#jobs:
#    build:
#        docker:
#            - image: cibuilds/hugo:latest
#        working_directory: ~/matbilodeau.github.io
#        steps:
#            - add_ssh_keys:
#                fingerprints:
#                    - "4e:ae:c5:01:39:ca:92:35:73:6d:8d:9a:8e:18:e3:db"
#            - checkout
#            - run:
#                name: Get current site
#                working_directory: ~/
#                command: git clone -b source git@github.com:matbilodeau.github.io.git public
#            - run:
#                name: Generate site
#                working_directory: ~/matbilodeau.github.io
#                command: HUGO_ENV=production hugo -d ~/public
#            - deploy:
#                name: Deploy to Github Pages
#                working_directory: ~/public
#                command: |
#                    git config credential.helper 'cache --timeout=120'
#                    git config user.email "mathieubilodeau000@gmail.com
#                    git config user.name "Deployment Bot"
#                    git add .
#                    git commit --allow-empty -m "Trigger deployment"
#                    git push -q git@github.com:matbilodeau.github.io.git master
#
#workflows:
#  version: 2
#  main:
#    jobs:
#    - build:
#        filters:
#          branches:
#            only: source


version: 2.0
jobs:
  checkout-existing:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - " ab:46:e4:40:bf:33:81:95:a8:85:da:53:76:7f:93:e6"
      - run:
          name: Pull main
          command: |
            mkdir public && cd ./public
            git init
            git remote add origin git@github.com:matbilodeau/matbilodeau.github.io.git
            git pull origin main
            git checkout main
      - persist_to_workspace:
          root: ~/project
          paths:
            - public


  build:
    working_directory: ~/project
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - attach_workspace:
          at: ~/tmp
      - add_ssh_keys:
          fingerprints:
            - " ab:46:e4:40:bf:33:81:95:a8:85:da:53:76:7f:93:e6"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: copy old files up
          command: cp -r ~/tmp/public ~/project/public
      - run:
          name: Run Hugo
          command: HUGO_ENV=production hugo -v
      - persist_to_workspace:
          root: ~/project
          paths:
            - public

  test:
    working_directory: ~/project
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: html check
          command: |
            htmlproofer ~/project/public --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external

  deploy-main:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - " ab:46:e4:40:bf:33:81:95:a8:85:da:53:76:7f:93:e6"
      - run:
          name: Update main with changes
          command: |
            cd ./public
            git config --global user.email "mathieubilodeau000@gmail.com"
            git config --global user.name "CircleCI_Bot"
            git add *
            commitMsg="CircleCI site rebuild at `date` [skip ci]"
            git commit -m "$commitMsg"
            git push origin main
workflows:
  version: 2
  build-and-deploy:
    triggers:
        filters:
          branches:
            only:
              - source
    jobs:
      - checkout-existing:
          filters:
            branches:
              only:
                - source
      - build:
          requires:
            - checkout-existing
      - test:
          requires:
            - build
      - deploy-main:
          requires:
            - test
